# Generated by Django 4.0.5 on 2022-06-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_answer_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='is_filled',
        ),
    ]
