# Generated by Django 4.0.5 on 2022-06-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_remove_response_is_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationaction',
            name='meta_data',
        ),
        migrations.AddField(
            model_name='integrationaction',
            name='input',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='integrationaction',
            name='steps_data',
            field=models.JSONField(default={}),
        ),
    ]
