# Generated by Django 4.0.5 on 2022-06-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_alter_integrationaction_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationaction',
            name='current_step',
        ),
        migrations.AlterField(
            model_name='integrationaction',
            name='type',
            field=models.CharField(choices=[('GOOGLE_DOCS', 'GOOGLE_DOCS'), ('DEMO', 'DEMO'), ('NONE_TYPE', 'NONE_TYPE')], default='NONE_TYPE', max_length=255),
        ),
    ]
