# Generated by Django 4.0.5 on 2022-06-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_remove_integrationaction_current_step_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationaction',
            name='steps_data',
        ),
        migrations.AddField(
            model_name='response',
            name='steps_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='integrationaction',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('STARTED', 'STARTED')], default='NOT_STARTED', max_length=255),
        ),
    ]
