# Generated by Django 4.0.5 on 2022-06-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0007_remove_integrationaction_steps_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='steps_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
